// SPDX-License-Identifier: AGPL-3.0-or-later
import { createHash } from 'node:crypto';
import { existsSync, mkdtempSync, readdirSync, readFileSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { afterAll, beforeAll, describe, expect, it } from 'vitest';
import { extractKeyframes } from '../../src/frames/extract-keyframes.js';
import { createRealFfmpegRunner } from '../../src/frames/ffmpeg-runner.js';
import type { StepTiming } from '../../src/segment/types.js';
import { createSyntheticVideo } from '../helpers/synthetic-video.js';

/**
 * AC2: proves this package actually shells out to real ffmpeg (per this
 * PRD's brief) against a hermetic, synthetic `testsrc` video generated by
 * ffmpeg itself - no captured webm anywhere in this test.
 */
describe('AC2: extractKeyframes (real ffmpeg)', () => {
  const workDir = mkdtempSync(path.join(tmpdir(), 'waggle-ingest-frames-'));
  const videoPath = path.join(workDir, 'video.mp4');
  const runner = createRealFfmpegRunner();

  const stepTimings: StepTiming[] = [
    {
      stepIndex: 0,
      actionRelMs: 1_500,
      settledRelMs: 2_000,
      clickPoint: { x: 10, y: 10 },
      route: '/',
    },
    { stepIndex: 1, actionRelMs: 4_000, settledRelMs: null, clickPoint: null, route: '/next' },
  ];
  const durationMs = 6_000;

  beforeAll(() => {
    createSyntheticVideo(videoPath, 8);
  }, 30_000);

  afterAll(() => {
    rmSync(workDir, { recursive: true, force: true });
  });

  it('writes before.png, click.png, settled.png (when present), and the 1fps sample strip, per step', async () => {
    const projectDir = mkdtempSync(path.join(tmpdir(), 'waggle-ingest-frames-project-'));
    const result = await extractKeyframes(
      runner,
      videoPath,
      projectDir,
      1,
      stepTimings,
      durationMs,
      { windowMs: 1_000, sampleIntervalMs: 500 }, // small window: keeps this test's spawn count low
    );

    const step0Dir = path.join(projectDir, 'steps', 'v1', 'step-000');
    expect(existsSync(path.join(step0Dir, 'before.png'))).toBe(true);
    expect(existsSync(path.join(step0Dir, 'click.png'))).toBe(true);
    expect(existsSync(path.join(step0Dir, 'settled.png'))).toBe(true);
    // -1000, -500, 0, +500, +1000 = 5 samples at a 500ms interval over a 1000ms window
    expect(readdirSync(step0Dir).filter((f) => f.startsWith('frame_t'))).toHaveLength(5);

    const step1Dir = path.join(projectDir, 'steps', 'v1', 'step-001');
    expect(existsSync(path.join(step1Dir, 'before.png'))).toBe(true);
    expect(existsSync(path.join(step1Dir, 'click.png'))).toBe(true);
    expect(existsSync(path.join(step1Dir, 'settled.png'))).toBe(false); // step 1 has no settle

    const step0Assets = result.assetsByStepIndex.get(0);
    expect(step0Assets).toEqual({
      before: 'steps/v1/step-000/before.png',
      click: 'steps/v1/step-000/click.png',
      settled: 'steps/v1/step-000/settled.png',
    });

    rmSync(projectDir, { recursive: true, force: true });
  });

  it('runs ffmpeg with the exact documented argv shape: -y -i <video> -ss <seconds> -frames:v 1 <out>', async () => {
    const projectDir = mkdtempSync(path.join(tmpdir(), 'waggle-ingest-frames-project-'));
    const result = await extractKeyframes(
      runner,
      videoPath,
      projectDir,
      1,
      [stepTimings[0] as StepTiming],
      durationMs,
      { windowMs: 0, sampleIntervalMs: 1_000 },
    );

    const clickFrame = result.frames.find((f) => f.role === 'click');
    expect(clickFrame?.argv).toEqual([
      '-y',
      '-i',
      videoPath,
      '-ss',
      '1.500',
      '-frames:v',
      '1',
      path.join(projectDir, 'steps', 'v1', 'step-000', 'click.png'),
    ]);

    rmSync(projectDir, { recursive: true, force: true });
  });

  it('is idempotent: two independent extraction runs produce byte-identical PNG output', async () => {
    const projectA = mkdtempSync(path.join(tmpdir(), 'waggle-ingest-frames-idem-a-'));
    const projectB = mkdtempSync(path.join(tmpdir(), 'waggle-ingest-frames-idem-b-'));

    const options = { windowMs: 500, sampleIntervalMs: 500 };
    const resultA = await extractKeyframes(
      runner,
      videoPath,
      projectA,
      1,
      stepTimings,
      durationMs,
      options,
    );
    const resultB = await extractKeyframes(
      runner,
      videoPath,
      projectB,
      1,
      stepTimings,
      durationMs,
      options,
    );

    expect(resultA.frames).toHaveLength(resultB.frames.length);

    const hashesA = resultA.frames.map((f) =>
      createHash('sha256').update(readFileSync(f.absolutePath)).digest('hex'),
    );
    const hashesB = resultB.frames.map((f) =>
      createHash('sha256').update(readFileSync(f.absolutePath)).digest('hex'),
    );

    expect(hashesB).toEqual(hashesA);

    rmSync(projectA, { recursive: true, force: true });
    rmSync(projectB, { recursive: true, force: true });
  }, 60_000);
});
