import type { NarrationWordsDocument } from '@waggle/narrate';
import type { BrandKit, Card } from '../brand/schema.js';
import type { RenderPreset } from '../presets.js';
import type { RenderTimeline } from '../timeline.js';
import { toTimelineMs } from '../timeline.js';
import { buildKaraokeCues, renderKaraokeText } from './ass-karaoke.js';
import { escapeAssText, toAssTime } from './ass-primitives.js';
import {
  ASS_STYLE_FORMAT,
  buildStyleRows,
  CAPTION_STYLE_NAME,
  INTRO_SUBTITLE_STYLE_NAME,
  INTRO_TITLE_STYLE_NAME,
  OUTRO_SUBTITLE_STYLE_NAME,
  OUTRO_TITLE_STYLE_NAME,
  WATERMARK_STYLE_NAME,
} from './ass-style.js';

/**
 * The complete `.ass` file a render burns in (prd-007 AC2).
 *
 * One libass pass renders every piece of text in the composition: the
 * karaoke captions, a text watermark, and the intro/outro card titles.
 * Routing all text through a single renderer is a deliberate choice over
 * mixing `drawtext` in for the cards, because `drawtext` needs an absolute
 * `fontfile=` path (which would put a machine-specific string into the
 * filter graph and break AC4's determinism claim) and because two text
 * renderers means two sets of font-fallback behaviour to reason about.
 *
 * `PlayResX`/`PlayResY` are set to the preset's own pixel dimensions, so
 * every size and margin computed from the brand kit's fractions is in
 * output pixels with no further scaling.
 */

export const ASS_EVENT_FORMAT =
  'Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text';

interface DialogueRow {
  readonly layer: number;
  readonly startMs: number;
  readonly endMs: number;
  readonly style: string;
  readonly text: string;
}

function renderDialogue(row: DialogueRow): string {
  return `Dialogue: ${row.layer},${toAssTime(row.startMs)},${toAssTime(row.endMs)},${row.style},,0,0,0,,${row.text}`;
}

/**
 * A card's two text lines, positioned explicitly.
 *
 * `\pos` rather than per-style margins: an ASS margin is measured from a
 * different edge depending on the alignment, which makes "title above,
 * subtitle below, both centred" surprisingly easy to get upside down.
 * Absolute coordinates against the declared `PlayResX`/`PlayResY` are
 * unambiguous, and they stay deterministic because both are the preset's
 * own pixel dimensions.
 */
function cardRows(
  card: Card | null,
  preset: RenderPreset,
  startMs: number,
  endMs: number,
  titleStyle: string,
  subtitleStyle: string,
): DialogueRow[] {
  if (card === null || !card.enabled || endMs <= startMs) {
    return [];
  }
  const centreX = Math.round(preset.width / 2);
  const titleSize = card.titleSizePct * preset.height;
  const hasSubtitle = card.subtitle !== '';
  // With a subtitle the pair is centred as a block; alone, the title sits
  // on the frame's own centre line.
  const titleY = Math.round(preset.height / 2 - (hasSubtitle ? titleSize * 0.45 : 0));
  const subtitleY = Math.round(titleY + titleSize * 0.95);

  const rows: DialogueRow[] = [];
  if (card.title !== '') {
    rows.push({
      layer: 2,
      startMs,
      endMs,
      style: titleStyle,
      text: `{\\an5\\pos(${centreX},${titleY})}${escapeAssText(card.title)}`,
    });
  }
  if (hasSubtitle) {
    rows.push({
      layer: 2,
      startMs,
      endMs,
      style: subtitleStyle,
      text: `{\\an5\\pos(${centreX},${subtitleY})}${escapeAssText(card.subtitle)}`,
    });
  }
  return rows;
}

export interface AssDocumentInput {
  readonly kit: BrandKit;
  readonly preset: RenderPreset;
  readonly timeline: RenderTimeline;
  /** `null` when the project has no narration; the document still carries cards and watermark. */
  readonly words: NarrationWordsDocument | null;
}

export interface AssDocument {
  readonly text: string;
  /** How many karaoke cues were emitted. Reported in the layer manifest. */
  readonly cueCount: number;
}

export function buildAssDocument(input: AssDocumentInput): AssDocument {
  const { kit, preset, timeline, words } = input;

  const header = [
    '[Script Info]',
    '; Generated by @waggle/compose (prd-007). Do not edit by hand.',
    'ScriptType: v4.00+',
    // WrapStyle 2 disables libass's own word wrapping: the cue builder has
    // already wrapped to the kit's character budget, and letting libass
    // re-wrap would put a break where no `\k` boundary expects one.
    'WrapStyle: 2',
    'ScaledBorderAndShadow: yes',
    'YCbCr Matrix: TV.709',
    `PlayResX: ${preset.width}`,
    `PlayResY: ${preset.height}`,
    '',
    '[V4+ Styles]',
    ASS_STYLE_FORMAT,
    ...buildStyleRows(kit, preset),
    '',
    '[Events]',
    ASS_EVENT_FORMAT,
  ];

  const rows: DialogueRow[] = [];

  let cueCount = 0;
  if (kit.captions.enabled && words !== null && words.words.length > 0) {
    const cues = buildKaraokeCues(words.words, {
      maxCharsPerLine: kit.captions.maxCharsPerLine,
      maxLinesPerCue: kit.captions.maxLinesPerCue,
    });
    cueCount = cues.length;
    for (const cue of cues) {
      rows.push({
        layer: 0,
        startMs: toTimelineMs(timeline, cue.startMs),
        endMs: toTimelineMs(timeline, cue.endMs),
        style: CAPTION_STYLE_NAME,
        text: renderKaraokeText(cue, kit.captions.karaokeStyle),
      });
    }
  }

  if (kit.watermark !== null && kit.watermark.kind === 'text') {
    // Body only: the intro and outro cards are already branded, and a
    // watermark sitting on top of a title card reads as a mistake.
    rows.push({
      layer: 1,
      startMs: timeline.bodyStartMs,
      endMs: timeline.bodyEndMs,
      style: WATERMARK_STYLE_NAME,
      text: escapeAssText(kit.watermark.text),
    });
  }

  rows.push(
    ...cardRows(
      kit.intro,
      preset,
      0,
      timeline.introMs,
      INTRO_TITLE_STYLE_NAME,
      INTRO_SUBTITLE_STYLE_NAME,
    ),
  );
  rows.push(
    ...cardRows(
      kit.outro,
      preset,
      timeline.outroStartMs,
      timeline.totalMs,
      OUTRO_TITLE_STYLE_NAME,
      OUTRO_SUBTITLE_STYLE_NAME,
    ),
  );

  const body = rows.map(renderDialogue);
  return { text: `${[...header, ...body].join('\n')}\n`, cueCount };
}
