import { spawnSync } from 'node:child_process';
import { existsSync, mkdirSync, mkdtempSync, readFileSync, statSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import path from 'node:path';
import {
  createDefaultManifest,
  PROJECT_SUBDIRS,
  WAGGLE_IR_SCHEMA_VERSION,
  WalkthroughFlowSchema,
  writeNextIrVersion,
} from '@waggle/ir';
import { NARRATION_WORDS_SCHEMA_VERSION, writeWordsJson } from '@waggle/narrate';
import { afterEach, beforeEach, describe, expect, it } from 'vitest';
import { runCli } from '../src/cli.js';
import { ExitCode } from '../src/exit-codes.js';

/**
 * prd-007 AC7: `waggle render --preset 16x9` on a fixture project.
 *
 * This is the command-level test: it drives the real CLI entry point, with
 * the real compositor and a real ffmpeg encode, and asserts on the exit
 * code and the file that lands on disk. `packages/compose` owns the
 * deeper render assertions (idempotency, kit swapping, graph determinism);
 * what this file proves is that the wiring between them is real.
 */

let projectDir = '';
let stdout = '';
let stderr = '';
const originalWrite = process.stdout.write.bind(process.stdout);
const originalErrorWrite = process.stderr.write.bind(process.stderr);

function ffmpeg(args: readonly string[]): void {
  const result = spawnSync('ffmpeg', [...args], { encoding: 'utf8' });
  if (result.status !== 0) {
    throw new Error(`ffmpeg fixture generation failed:\n${result.stderr ?? ''}`);
  }
}

/**
 * Stages a complete, narrated project with a synthetic recording.
 *
 * The media is generated by ffmpeg rather than committed: a checked-in
 * sample MP4 would be the largest artifact in the repository and would
 * need regenerating for every change of duration or aspect ratio.
 */
function stageProject(): string {
  const dir = mkdtempSync(path.join(tmpdir(), 'waggle-cli-render-'));
  for (const subdir of PROJECT_SUBDIRS) {
    mkdirSync(path.join(dir, subdir), { recursive: true });
  }

  writeFileSync(
    path.join(dir, 'waggle.json'),
    `${JSON.stringify(
      {
        ...createDefaultManifest('render-fixture'),
        createdAt: '2026-08-20T00:00:00.000Z',
        // A small 16x9 so a full-fidelity render finishes in seconds. The
        // command under test is still `--preset 16x9`.
        presets: { '16x9': { width: 640, height: 360, fps: 24 } },
      },
      null,
      2,
    )}\n`,
    'utf8',
  );

  ffmpeg([
    '-hide_banner',
    '-nostdin',
    '-y',
    '-loglevel',
    'error',
    '-f',
    'lavfi',
    '-i',
    'testsrc2=size=640x360:rate=24:duration=2.5',
    '-f',
    'lavfi',
    '-i',
    'sine=frequency=220:duration=2.5',
    '-c:v',
    'libx264',
    '-preset',
    'ultrafast',
    '-pix_fmt',
    'yuv420p',
    '-c:a',
    'aac',
    '-b:a',
    '96k',
    '-map_metadata',
    '-1',
    path.join(dir, 'steps', 'recording.mp4'),
  ]);
  ffmpeg([
    '-hide_banner',
    '-nostdin',
    '-y',
    '-loglevel',
    'error',
    '-f',
    'lavfi',
    '-i',
    'sine=frequency=440:duration=2.5',
    '-c:a',
    'libmp3lame',
    '-b:a',
    '96k',
    '-map_metadata',
    '-1',
    path.join(dir, 'narration', 'audio.mp3'),
  ]);

  const cursorTrail = Array.from({ length: 26 }, (_, i) => ({
    t: i * 100,
    x: 200 + i * 20,
    y: 300 + (i % 5) * 12,
  }));
  writeNextIrVersion(
    dir,
    WalkthroughFlowSchema.parse({
      title: 'CLI render fixture',
      steps: [
        {
          type: 'navigate',
          url: 'https://demo.example.com/dashboard',
          waggle: { classification: 'navigate', routeAfter: '/dashboard', masked: false },
        },
      ],
      waggle: {
        schemaVersion: WAGGLE_IR_SCHEMA_VERSION,
        recordedViewport: { w: 1280, h: 720, dpr: 1 },
        startEpochMs: 1_700_000_000_000,
        cursorTrail,
        clicks: [
          { t: 1200, x: 640, y: 360, down: true },
          { t: 1290, x: 640, y: 360, down: false },
        ],
        sourceRecording: { videoRef: 'steps/recording.mp4', durationMs: 2500 },
      },
    }),
  );

  writeWordsJson(path.join(dir, 'narration', 'words.json'), {
    schemaVersion: NARRATION_WORDS_SCHEMA_VERSION,
    provider: 'fixture',
    sourceText: 'Open the dashboard and apply a filter.',
    durationMs: 2500,
    words: [
      { word: 'Open', startMs: 0, endMs: 350 },
      { word: 'the', startMs: 360, endMs: 600 },
      { word: 'dashboard', startMs: 620, endMs: 1150 },
      { word: 'and', startMs: 1180, endMs: 1400 },
      { word: 'apply', startMs: 1420, endMs: 1800 },
      { word: 'a', startMs: 1820, endMs: 1950 },
      { word: 'filter.', startMs: 1980, endMs: 2400 },
    ],
  });

  return dir;
}

beforeEach(() => {
  stdout = '';
  stderr = '';
  process.stdout.write = ((chunk: string) => {
    stdout += chunk;
    return true;
  }) as typeof process.stdout.write;
  process.stderr.write = ((chunk: string) => {
    stderr += chunk;
    return true;
  }) as typeof process.stderr.write;
  projectDir = stageProject();
});

afterEach(() => {
  process.stdout.write = originalWrite;
  process.stderr.write = originalErrorWrite;
});

describe('AC7: waggle render', () => {
  it('renders a watchable MP4 from the fixture project at --preset 16x9', async () => {
    const code = await runCli([
      'node',
      'waggle',
      'render',
      '--project',
      projectDir,
      '--preset',
      '16x9',
    ]);

    expect(code).toBe(ExitCode.SUCCESS);
    expect(stdout).toContain('Render written:');
    expect(stdout).toContain('Preset: 16x9 (640x360 at 24fps, native)');
    expect(stdout).toContain('Brand kit: default');

    const output = path.join(projectDir, 'renders', 'walkthrough.v1.default.16x9.mp4');
    expect(existsSync(output)).toBe(true);
    expect(statSync(output).size).toBeGreaterThan(5_000);

    // Every layer is reported, including ADR-007's reserved empty slot.
    expect(stdout).toContain('+ synthetic-cursor');
    expect(stdout).toContain('+ click-ripples');
    expect(stdout).toContain('+ captions');
    expect(stdout).toContain('- picture-in-picture: reserved slot (ADR-007)');

    // ADR-011: the render metadata says whether the preset was reframed.
    const metadata = JSON.parse(readFileSync(`${output}.render.json`, 'utf8')) as {
      reframe: string;
      backend: string;
    };
    expect(metadata.reframe).toBe('native');
    expect(metadata.backend).toBe('ffmpeg');
  });

  it('prints the command and writes nothing under --dry-run', async () => {
    const code = await runCli(['node', 'waggle', 'render', '--project', projectDir, '--dry-run']);
    expect(code).toBe(ExitCode.SUCCESS);
    expect(stdout).toContain('Dry run: nothing was encoded.');
    expect(existsSync(path.join(projectDir, 'renders', 'walkthrough.v1.default.16x9.mp4'))).toBe(
      false,
    );
  });

  it('exits PRESET_UNKNOWN and lists the known ids for a bad preset', async () => {
    const code = await runCli([
      'node',
      'waggle',
      'render',
      '--project',
      projectDir,
      '--preset',
      'vertical',
    ]);
    expect(code).toBe(ExitCode.PRESET_UNKNOWN);
    expect(stderr).toContain('Known presets:');
  });

  it('exits BRAND_KIT_INVALID for a kit that is not on disk', async () => {
    const code = await runCli([
      'node',
      'waggle',
      'render',
      '--project',
      projectDir,
      '--brand-kit',
      'nope',
    ]);
    expect(code).toBe(ExitCode.BRAND_KIT_INVALID);
    expect(stderr).toContain('not found');
  });

  it('exits RENDER_INPUT_MISSING when the source recording is gone', async () => {
    const { rmSync } = await import('node:fs');
    rmSync(path.join(projectDir, 'steps', 'recording.mp4'));
    const code = await runCli(['node', 'waggle', 'render', '--project', projectDir]);
    expect(code).toBe(ExitCode.RENDER_INPUT_MISSING);
    expect(stderr).toContain('does not exist');
  });

  it('still resolves the project the way every other command does', async () => {
    const code = await runCli(['node', 'waggle', 'render', '--project', tmpdir()]);
    expect(code).toBe(ExitCode.PROJECT_NOT_FOUND);
  });
});
