import { readFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import {
  type CaptureEvent,
  CaptureEventSchema,
  type SessionMeta,
  SessionMetaSchema,
} from '@waggle/extension';

/**
 * The real six-step recording checked into
 * test/fixtures/six-step-session/, generated by
 * apps/extension/scripts/generate-ingest-fixture.ts against the real
 * `@waggle/extension` content-script/route-main-world bundles and the
 * real fixture app - see that script's header for exactly what is
 * genuine capture output and what one event (a settle event) is
 * synthesized and why.
 */
const FIXTURE_DIR = path.join(
  path.dirname(fileURLToPath(import.meta.url)),
  '../fixtures/six-step-session',
);

export interface SixStepFixture {
  readonly events: CaptureEvent[];
  readonly meta: SessionMeta;
  readonly dir: string;
}

export function loadSixStepFixture(): SixStepFixture {
  const meta = SessionMetaSchema.parse(
    JSON.parse(readFileSync(path.join(FIXTURE_DIR, 'meta.json'), 'utf8')),
  );
  const eventsRaw = readFileSync(path.join(FIXTURE_DIR, 'events.jsonl'), 'utf8');
  const events = eventsRaw
    .split('\n')
    .filter((line) => line.trim() !== '')
    .map((line) => CaptureEventSchema.parse(JSON.parse(line)));
  return { events, meta, dir: FIXTURE_DIR };
}
